### ISSUE TITLE
Imports with "as" in the names fail to compile

### ISSUE THREAD

**Issue by Lexico** [chitter99/typescript-declaration-webpack-plugin#5]
On line 46 of your index.js you're looking for "as" in the import line, just to check if you should treat it as an "import * from Class" or "import * as name from Class", but this fails if the class name (like in this very example) contains the string "as". 
Both strings here would match the "line.indexOf('as') != -1" condition here.
You can fix this just by adding spaces on the search string.

**Comment by chitter99** [comment]
Solved by merge 465405e48b89d769111f63210b4bbb2db7d173c1
