### ISSUE TITLE
incorrectly closed bracket stopping interfaces and classes being bundled

### ISSUE THREAD

**Issue by DaJaffaMan** [chitter99/typescript-declaration-webpack-plugin#6]
when exporting an interface or class this isn't being picked up by the plugin because of an missed bracket.

https://github.com/chitter99/typescript-declaration-webpack-plugin/blob/master/index.js#L81

**Comment by thdk** [comment]
Example output:

```
/// <reference types="react" />

    compiler: string;
    framework: string;
}
export declare const Hello: (props: HelloProps) => JSX.Element;
```

Generated from:

**index.tsx**

`export { HelloProps } from "./components/hello/index";`

**components/hello/index.tsx**
```
import * as React from "react";

export interface HelloProps {
    compiler: string;
    framework: string;
};

export const Hello = (props: HelloProps) => {
    React.useEffect(() => {
        console.log(`Hello from ${props.compiler} and ${props.framework}!`)
    }, []);

    return <></>;
}
```

**Comment by DaJaffaMan** [comment]
https://github.com/chitter99/typescript-declaration-webpack-plugin/pull/7
